### ISSUE TITLE
bower package is not found

### ISSUE THREAD

**Issue by tonyfast** [phosphorjs/playground#1]
I tried to load the playground using bower, but it is not being found.

```
$ bower install phosphor-playground
bower ENOTFOUND     Package phosphor-playground not found
```

**Comment by dwillmer** [comment]
Hi Tony, 

Have you tried

*bower install phosphorjs/playground*

?

**Comment by tonyfast** [comment]
That did the trick.  Thanks Dave.  The readme needs a small a change.

**Comment by dwillmer** [comment]
Yep, pull request created already, thanks for raising this! :)
