### ISSUE TITLE
How do I run the sidecar examples?

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/playground#12]
Do I have an old version of tornado or sth?

```
λ python .\sidecar.py
Traceback (most recent call last):
  File ".\sidecar.py", line 102, in <module>
    main(sys.argv)
  File ".\sidecar.py", line 92, in main
    loop.add_callback(webbrowser.open, url)
TypeError: add_callback() takes exactly 2 arguments (3 given)
```

**Comment by blink1073** [comment]
Could be, I have tornado 4.2.1.  I'll put READMEs in each of the folders on Monday.

**Comment by blink1073** [comment]
To run sidecar:
Run `ipython console` in one terminal
Run `python sidecar.py` in another.
From the console, run something like `from IPython.display import HTML; HTML('hi')` and it should show up in the browser.
